name: JMeter Tests - Demoblaze

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar JMeter
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk xvfb
        JMETER_VERSION="5.4.1"  # Última versión estable
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
        tar -xzf apache-jmeter-${JMETER_VERSION}.tgz
        mv apache-jmeter-${JMETER_VERSION} jmeter
        echo "$(pwd)/jmeter/bin" >> $GITHUB_PATH  # Agregar JMeter al PATH
        # Instalar JMeter Plugins Manager
        wget -P jmeter/lib/ext https://jmeter-plugins.org/files/packages/jpgc-cmd-2.2.zip
        unzip jmeter/lib/ext/jpgc-cmd-2.2.zip -d jmeter/lib/ext/
        rm jmeter/lib/ext/jpgc-cmd-2.2.zip
        
        # Instalar plugin necesario (Standard Set)
        wget -P jmeter/lib/ext https://jmeter-plugins.org/files/packages/jpgc-standard-2.9.zip
        unzip jmeter/lib/ext/jpgc-standard-2.9.zip -d jmeter/lib/ext/
        rm jmeter/lib/ext/jpgc-standard-2.9.zip

    - name: Verificar instalación de JMeter
      run: jmeter -v

    - name: Ejecutar pruebas de carga con JMeter en Demoblaze
      run: jmeter -n -t demoblaze-test.jmx -l result.jtl -e -o report

    - name: Subir reportes como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-demoblaze-report
        path: report/
