name: JMeter Tests - Demoblaze

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar JMeter
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
        tar -xvzf apache-jmeter-5.6.2.tgz
        echo "JMETER_HOME=$(pwd)/apache-jmeter-5.6.2" >> $GITHUB_ENV
        echo "$JMETER_HOME/bin" >> $GITHUB_PATH

    - name: Verificar instalación de JMeter
      run: jmeter -v

    - name: Ejecutar pruebas de carga con JMeter en Demoblaze
      run: jmeter -n -t tests/demoblaze-test.jmx -l result.jtl -e -o report

    - name: Subir reportes como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-demoblaze-report
        path: report/
